# Generated by Django 3.2.6 on 2021-08-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='page',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=11),
        ),
    ]
