# Generated by Django 3.2.6 on 2021-08-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20210805_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
