# Generated by Django 3.2.6 on 2021-08-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_page_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
