# Generated by Django 3.2.6 on 2021-08-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_alter_page_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
